### ISSUE TITLE
コンデンサー C1 の値が矛盾している？

### ISSUE THREAD

**Issue by mikecat** [v9938/MSX_SimpleCartridge#1]
`README.md` の部品表に

> C1 | コンデンサー0.01uF (104)

とありますが、一般的には104は0.1μF、0.01μFは103であり、矛盾しているのではないかという印象があります。

参考

* [コンデンサーの読み方](https://www.jarl.org/Japanese/7_Technical/lib1/konden.htm)
* [コンデンサ容量値・定格電圧の読み方 | Spiceman](https://spiceman.jp/capacitor-value/)
* [抵抗値・コンデンサの読み方｜評価試験用電源なら松定プレシジョン](https://www.matsusada.co.jp/column/resistance-condenser.html)

**Comment by v9938** [comment]
104が正しいため修正しました。
