### ISSUE TITLE
「ジャンパ設定について」の表が誤解を招く

### ISSUE THREAD

**Issue by mikecat** [v9938/MSX_SimpleCartridge#2]
`README.md` の「ジャンパ設定について」の表において、A14(29Pin) の下側が「GND」となっていますが、
基板の現物 (訳あり品 2021/09 Rev:D) を確認したところ、A14の下側はA15に繋がっていました。
さらに、ここに上がっている回路図 `simpleCart_RevC.pdf` においても、IC1のA14の接続先はA14とA15になっており、GNDは選択肢に無いようです。
「DIP版」というだけでなく、対象のRevを明示したほうがいいと思います。

なお、下の「EPROM設定例」においても「A14(29Pin)」が「下(GND)」となっており、同様の問題があります。

**Comment by v9938** [comment]
当該部分の追記およびRevDの回路図を追加しました。
